alias gpom="git push origin master"
alias notes="vim notes-\$(date +%F)"
alias tmux="tmux -2"
alias weecolors="weechat -c | sed $'s/38;/48;/g; s/$/\e[m/'"
alias gpg-fix-cache="touch dummy.in; gpg --output dummy.asc --encrypt -r F637E333 dummy.in; gpg --output dummy.out --decrypt dummy.asc; rm dummy.{in,out,asc}"
